"""grading

Revision ID: 8475d49b0455
Revises: 5d33c94d43df
Create Date: 2026-09-03 23:28:40.866365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '8475d49b0455'
down_revision: Union[str, Sequence[str], None] = '5d33c94d43df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answer_grades',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('submission_id', sa.String(), nullable=False),
    sa.Column('answer_box_id', sa.String(), nullable=False),
    sa.Column('max_score', sa.Integer(), nullable=False),
    sa.Column('llm_score', sa.Float(), nullable=True),
    sa.Column('llm_feedback', sa.String(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('raw_response', sa.String(), nullable=True),
    sa.Column('override_score', sa.Float(), nullable=True),
    sa.Column('override_feedback', sa.String(), nullable=True),
    sa.Column('overridden_by', sa.String(), nullable=True),
    sa.Column('overridden_at', sa.DateTime(), nullable=True),
    sa.Column('needs_manual_review', sa.Boolean(), nullable=False),
    sa.Column('review_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['answer_box_id'], ['answer_boxes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['overridden_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id', 'answer_box_id', name='uq_grade_submission_box')
    )
    # add_column doesn't create the Postgres enum type the way create_table
    # does, so it has to be created explicitly first.
    grading_status = postgresql.ENUM(
        'ungraded', 'queued', 'grading', 'graded', 'failed', name='grading_status'
    )
    grading_status.create(op.get_bind())

    # server_default matters: without it, adding a NOT NULL column to a
    # submissions table that already has rows fails outright. Existing
    # submissions are, correctly, ungraded.
    op.add_column('submissions', sa.Column('grading_status', grading_status, nullable=False, server_default='ungraded'))
    op.add_column('submissions', sa.Column('grading_error', sa.String(), nullable=True))
    op.add_column('submissions', sa.Column('graded_at', sa.DateTime(), nullable=True))
    op.add_column('submissions', sa.Column('released_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'released_at')
    op.drop_column('submissions', 'graded_at')
    op.drop_column('submissions', 'grading_error')
    op.drop_column('submissions', 'grading_status')
    op.drop_table('answer_grades')
    postgresql.ENUM(name='grading_status').drop(op.get_bind())
    # ### end Alembic commands ###
